GlobalPlanner:

  allow_unknown: false

  default_tolerance: 0.2

  visualize_potential: true #false

  use_dijkstra: false #true

  use_quadratic: true

  use_grid_path: false

  old_navfn_behavior: false

 

  lethal_cost: 253

  neutral_cost: 66 #50

  cost_factor: 0.55 #3.0

  publish_potential: true

  orientation_mode: 0

  orientation_window_size: 1

