KinoAstarPlanner:

  allow_unknown: false

  default_tolerance: 0.2

  visualize_potential: true #false

#  use_dijkstra: false #true

#  use_quadratic: true

#  use_grid_path: false

  old_navfn_behavior: true

 

  lethal_cost: 253

  neutral_cost: 66 #50

  cost_factor: 0.55 #3.0

#  publish_potential: true

  orientation_mode: 0

  orientation_window_size: 1

  max_tau: 0.6
  init_max_tau: 0.8
  max_vel: 3
  max_acc: 2
  w_time: 10.0
  horizon: 50.0
  time_resolution: 0.8
  lambda_heu: 5.0
  check_num: 5
  c_effi: 0.001

