local_costmap:

  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true

  width: 7
  height: 7
  resolution: 0.1
  transform_tolerance: 0.5

  # plugins:
  #   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#  robot_base_frame: base_footprint
#  static_map: true
#  rolling_window: false
